### ISSUE TITLE
Emails that include attachment bigger that 100 KB in size are not forwarded

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/fx-private-relay#1049]
**Build:**
Stage

**Affected platforms:**
Windows 10 64-bit

**Browsers tested on:**
Firefox

**Preconditions:**
The user has a few aliases already added.

**Steps to reproduce:**

1. Navigate to https://stage.fxprivaterelay.nonprod.cloudops.mozgcp.net and log in using an existing account. 
2. Select an alias with Forwarded status on and copy it.
3. Go to email client and send an email to this alias with an attachment that has 99.9/ 101 KB in size. 
4. Verify inbox.

**Actual result:**
Email is not received. Emails that include attachments of/ bigger that 100 KB are not forwarded.

**Expected result:**
Emails that include attachments up to 150 KB are forwarded.

**Inbox:**
![emails 99 3 KB forwarded](https://user-images.githubusercontent.com/79697848/131358139-a38a068f-98b1-4329-ac93-9b074cf3558f.PNG)

**Sent Mail:** (email not available in inbox)
![emails 101 KB not forwarded](https://user-images.githubusercontent.com/79697848/131359141-f3a3e196-a8bc-4075-ac0e-4c496ff16226.PNG)

**Comment by macks2008** [comment]
Not sure if the attachment is your problem (I'm just passing by), but I was about to open an issue asking what it would take to support bigger attachments. If whoever actually answers this happens to know, please mention me

**Comment by Bianca-O** [comment]
The email size limit was changed to 10 MB. Now the emails that contain attachments up to 7.3 MB are sent and received. Closing this issue.

**Comment by macks2008** [comment]
wonderful. That's about 1/5 of what Gmail supports... 
I still have questions, such as how do I know if an email got rejected for being too big (so I can let the sender know)? Will I get an empty version of the original which I can directly reply to, or would I have to reveal my "real" address?
Would be nice if there wasn't a limit at all, since the server doesn't have to retain anything except the source that needs to get the replies. okay obviously there has to be some limit, but you can at least try to imagine it as an email datastream right?

**Comment by Vinnl** [comment]
Hi @macks2008, please be aware that this isn't officially released yet; once it's generally available, it will be announced on relay.firefox.com.

Unfortunately, we are bound by limits set by our service provider, with whom we're currently working to raise the limit as much as possible. I don't have the answers to your other questions, unfortunately, but if you [contact support](https://accounts.firefox.com/support/?utm_source=https://github.com], I think they might be able to assist further.
