### ISSUE TITLE
outlook.com classified a forwarded from relay.firefox.com email as spam

### ISSUE THREAD

**Issue by galich** [mozilla/fx-private-relay#1153]
1. go https://store.irobot.com/default/register
2. use email alias generated by Relay and redirecting to name@outlook.com
3. Relay reports 2 emails forwarded and that there was a `soft "bounce" from your email provider`
4. outlook.com shows only 1 email in spam folder, classified as spam most likely because of the domain

**Comment by groovecoder** [comment]
Another instance: https://discourse.mozilla.org/t/firefox-relay-does-not-forward-received-emails/

**Comment by groovecoder** [comment]
and an AMO review: https://addons.mozilla.org/en-US/firefox/addon/private-relay/reviews/1761188/

**Comment by galich** [comment]
I've tried again with different alias from relay and it worked just as expected. 🎉 
Because last time I clicked "Not spam", I've made a new account on outlook.com and did whole process again. It also worked as expected. 🎉 

My guess is that Outlook have trained to trust mails from Relay by now.

Feel free to close this issue.

**Comment by groovecoder** [comment]
More instances: https://www.reddit.com/r/firefox/comments/qx9nek/whats_going_on_with_firefox_relay/

**Comment by groovecoder** [comment]
Something to check might be to see if our `return-path` and `from` need to be aligned? Some articles about Outlook deliverability mentioned that.

**Comment by groovecoder** [comment]
Update: it seems when Outlook users receive spam emails thru their Relay aliases, Outlook marks the spam as coming from Relay.

Outlook sends spam bounces back to Relay with a message like: `Message considered as spam ...`

So, to improve deliverability to outlook, I propose:
1. When we receive a bounce for a user,
   * if the bounce details include spam , instead of setting bounce pause on the account, set a new `auto_block_spam` field.
2. When we receive any email for a user with `auto_block_spam`,
   * if the SES `spamVerdict` is TRUE,
      * don’t forward the email.

This should automatically stop us from sending any more spam to the user after Outlook as bounced a first spam message back.
