### ISSUE TITLE
Placeholder text is missing from the “Enter alias prefix” field of the “Create a new custom alias” modal

### ISSUE THREAD

**Issue by AOiegas** [mozilla/fx-private-relay#1505]
#### Build:
- Stage;

#### Affected Platforms:
- Windows 10;

#### Browsers tested on:
- Firefox, latest version;

#### Prerequisites:
- Be signed in into a Firefox Relay account with an active subscription;
- Have a Subdomain (Custom Domain Name) set;

#### Steps to reproduce:
1. Go to the Relay Dashboard;
2. Click on the “Generate New Alias” button;
3. In the opened drop-down menu, click on the “@<subdomain> Alias” option;
4. Observe the “Enter alias prefix” field in the lower half of the modal; 

#### Expected result:
- The field should contain a placeholder text: e.g “coffee”;

#### Actual result:
- There is no placeholder text displayed;

#### Notes:
- I think the example in the placeholder text will clear any confusion a new user of this feature might have regarding to what they have to introduce;
- See attached media:
Figma reference:
![image](https://user-images.githubusercontent.com/85748693/151525452-cfc4d312-28fc-458f-a6fc-45d9e24cb471.png)
Stage:
![image](https://user-images.githubusercontent.com/85748693/151525512-4cad2b0d-7e05-42f0-be4b-835d9a1b9535.png)

**Comment by Vinnl** [comment]
Pff, I spent so much time discussin what this should actually look like, that I forgot to add it :P It will be fixed in https://github.com/mozilla/fx-private-relay/pull/1508

However, note that the default browser behaviour is to not show the placeholder when the input field is focused, which it is by default. Thus, after the fix, it will only show up when clicking outside of the input field.
