### ISSUE TITLE
Do not send events from specific loggers to Sentry

### ISSUE THREAD

**Issue by say-yawn** [mozilla/fx-private-relay#1556]
# About this Issue
Some of the loggers are showing duplicate events on Sentry along with the actual exception with stack trace being recorded on Sentry (see example [here](https://sentry.prod.mozaws.net/operations/fx-private-relay-prod/issues/18254312/?query=is%3Aunresolved) and [here](https://sentry.prod.mozaws.net/operations/fx-private-relay-prod/issues/14916780/?query=is%3Aunresolved)). Since certain loggers (like `request.summary`) are being recorded on Sentry with no stack trace while the actual exception is also being captured, we should stop sending events with no stack trace that are a duplicate of the actual exception from being logged on Sentry.

# Acceptance Criteria
`request.summary` should stop sending [events](https://sentry.prod.mozaws.net/operations/fx-private-relay-prod/?query=logger%3Adjango.security.DisallowedHost) to Sentry
`django.security.DisallowedHost` should stop sending [events](https://sentry.prod.mozaws.net/operations/fx-private-relay-prod/?query=logger%3Adjango.security.DisallowedHost) to Sentry (except for 3 hosts that need investigation #1557)

**Comment by jwhitlock** [comment]
In PR #1578, we're raising ``SuspiciousOperation`` to protect from inconsistent data (setting a premium feature flag for a non-premium feature), for the side-effect of returning a 400 error to the user. We'll need to ensure that these types of bug checks 1) result in a traceback in Sentry, and 2) return a 400 rather than a 50x to our users.
