### ISSUE TITLE
[Context Menu] "Generate Email Alias" in context menu shouldn’t be displayed on login forms or on fields other than email field

### ISSUE THREAD

**Issue by sv-hyacoub** [mozilla/fx-private-relay#198]
### Affected versions

* Nightly 77.0a1
* Private Relay add-on version 1.2.0 - https://drive.google.com/file/d/1OqZCFEwHrbUTH0q1dQUJBI43qVBaM3Hw/view

### Affected platforms

* Windows 10 and 7 x64
* Mac OS X 10.14
* Ubuntu 18.04

### Steps to reproduce

1. Launch the latest Nightly.
2. Install the Private Relay add-on and sign in.
3. Go to facebook.com.
4. Right click on the "Password" field and observe the context menu.
5. Right click on any of the field in the Sign Up form.

### Expected behavior

"Generate Email Alias" in context menu shouldn’t be displayed on login forms or on fields other than email field.

### Actual behavior

"Generate Email Alias" in context menu is displayed on login forms or on fields other than email field.
![Screenshot 2020-04-24 at 11 02 07](https://user-images.githubusercontent.com/15101135/80189468-60883680-861b-11ea-926e-a27ba74cc96a.png)

**Comment by groovecoder** [comment]
We'll use https://github.com/mozilla/fx-private-relay/issues/191 for handling relay addresses on login pages/forms rather than sign-up pages/forms.

We're using the context menu as a global "fallback" UI in case the add-on can't detect an email input field, so I think we'd rather have it show on these "false positives" than to miss some forms completely. So, closing this as "wontfix"
