### ISSUE TITLE
Mask status changes when the user clicks the link in Promotionals pop-up and gets back to previous page

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/fx-private-relay#2023]
**Build:**
Stage

**Affected platforms:**
Windows 10

**Browsers tested on:**
Firefox, latest release

**Preconditions:**
The user does not have an active subscription.
At least one mask is available in the list.

**Steps to reproduce:**
1. Go to Relay homepage and log in.
2. Expand one mask card and click the Promotionals (Premium only) option.
3. Click "Upgrade now"/ "Join the Relay Premium waitlist" link if the user is in a premium available country/ premium not available country.
4. Click the browser's "Back" button.
5. Observe the status of the card.

**Actual result:**
The status of the card is changed to Block all. The "All" circle is also highlighted when you repeat the steps one more time.

**Expected result:**
The status doesn't change.

**Notes:**
N/A

![status changes to block all](https://user-images.githubusercontent.com/79697848/171204935-b5340365-c23b-481b-a09d-8d05f6ba61d4.gif)

**Comment by Vinnl** [comment]
I spent a bit of time diving into this this morning, so sharing my findings so far. The root of the problem is that `<PromotionalTrackStop>`, and with that its child `<PromotionalTooltip>`, are located within the element with `ref={trackRef}` (i.e. `.track`). That means that when the tooltip opens, `.track` is suddenly wider, and thus [`useSlider`](https://react-spectrum.adobe.com/react-aria/useSlider.html) concludes that the slider track is wider, and clicking inside it on the right-hand side (e.g. in the popup) should select the right-most entry ("block all").

The solution is probably to move `<PromotionalTrackStop>` outside of `.track`, but that makes it harder to position it on top of the track. To be continued.

**Comment by Bianca-O** [comment]
This issue is verified as fixed on Stage under Windows 10. The mask status doesn't change anymore.
![new situation](https://user-images.githubusercontent.com/79697848/171855029-bd1f2536-3d9d-4ab4-91b9-64095a9a1696.gif)
