### ISSUE TITLE
Clicking on the “See more FAQs about Firefox Relay” link redirects the Firefox user to the bottom of the FAQs page

### ISSUE THREAD

**Issue by AOiegas** [mozilla/fx-private-relay#2187]
#### Build:
- Stage;
- Production;

#### Affected Platforms:
- Windows 10;

#### Browsers tested on:
- Firefox, Release version;

#### Prerequisites:
- Do NOT be signed in into a Firefox Relay account;

#### Steps to reproduce:
1. Go to the Relay home/landing page;
2. Scroll down to the FAQs section at the bottom of the page;
3. Click on the “See more FAQs about Firefox Relay” link;
4. Observe the results;

#### Expected result:
- Clicking on the link redirects the user to the top of the FAQs page;

#### Actual result:
- Clicking on the link redirects the user to the bottom of the FAQs page instead;

#### Notes:
- This happens only on Firefox. Chrome and Edge scroll the user to the top of the page;
- See attached media:
![linkfaq](https://user-images.githubusercontent.com/85748693/178439465-372ce8f9-c149-4bc6-8c85-7e7a465be9ca.gif)

**Comment by joaonunomota** [comment]
I haven't been able to reproduce this with version 112.0.1 (64-bit) of Firefox on Windows 10. Is there any more testing needed to confirm if this is no longer an issue?

![example](https://user-images.githubusercontent.com/16689477/233300327-7dc76148-95a5-4343-a499-de5e0db733ee.gif)

**Comment by Vinnl** [comment]
Thanks for looking into this. It looks like Next.js now [scrolls to the top by default](https://nextjs.org/docs/api-reference/next/link#disable-scrolling-to-the-top-of-the-page), which I think was added in https://github.com/vercel/next.js/issues/42492 after this issue was created. So I think this can be closed.

**Comment by vadym-lohvynovych** [comment]
On my project we have skeletons which we need to show while new page is loading, so once new page started loading we needed to show skeleton and scroll to the top immediately because if we do not scroll user will see bottom of the page if his scroll position was not 0.
Here's the solution which can also help you:
You can catch route change event and scroll the page programatically (there are also `routeChangeComplete` and routeChangeError events)
`useEffect(() => {
    const handleStart = (path: AppPath, config: { shallow: boolean }) => {

      if (!config.shallow) {
        window.scrollTo(0, 0);
      }
    };

    router.events.on('routeChangeStart', handleStart);

    return () => {
      router.events.off('routeChangeStart', handleStart);
    };
  }, [router]);`
