### ISSUE TITLE
Tab navigation issue on Relay dashboard

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/fx-private-relay#2213]
**Build:**
Stage

**Affected platforms:**
Windows 10

**Browsers tested on:**
Firefox, latest release

**Preconditions:**
At least one mask card is expanded.

**Steps to reproduce:**
1. Go to Relay page and log in using an existing account with or without an active subscription.
2. Use the Tab key to navigate through the page.

**Actual result:**
The "Click to copy" button doesn't have a focus effect. 
From "None" option, the Tab key gets to "Delete" button skipping the "Promotionals" and "All" options.

**Expected result:**
The "Click to copy" button has a focus effect when using the Tab key.
The Tab key goes through all the options: "None", "Promotionals" and "All" before getting to "Delete" button.

**Notes:**
N/A

![TAB navigation issue](https://user-images.githubusercontent.com/79697848/179526746-77762542-3493-43a9-b7d0-986fb1c31566.gif)

**Comment by Vinnl** [comment]
Thank you so much for reporting this! This is important to get right so that people with motor issues, or who prefer using the keyboard for other reasons, can use our website.

Note that "None", "Promotionals" and "All" are all reachable by keyboard, just not by pressing tab - once the current option is focused, you can use the arrow keys to switch between the different options. I'll check with UX if we can come up with a design that makes that clearer.
