### ISSUE TITLE
The “Trackers Removed” counter from the individual email mask cards is missing

### ISSUE THREAD

**Issue by AOiegas** [mozilla/fx-private-relay#2233]
#### Build:
- Stage;

#### Affected Platforms:
- Windows 10;
- Android 11;

#### Browsers tested on:
- Firefox, Release version;
- Chrome, Release version;

#### Prerequisites:
- Be signed in into a Firefox Relay account;
- Have at least one mask created;

#### Steps to reproduce:
1. Go to the Relay dashboard;
2. Observe the individual email mask cards;

#### Expected result:
- The email mask cards should display a “Trackers Removed” counter;

#### Actual result:
- The email mask cards are missing the “Trackers Removed” counter;

#### Notes:
- This happens for both Premium and Free users;
- I was able to see the counter a single time for a newly created Premium account, but there was no counter for the total number of trackers in the header. Then, after receiving a mail with trackers removed the situation changed back and I was not able to reproduce it again;
- See attached media:
![nocounter](https://user-images.githubusercontent.com/85748693/180408212-a02a2634-fb8a-4a53-8cf5-ce9a65a1d1d4.gif)

**Comment by Bianca-O** [comment]
This issue is verified as fixed on stage under Windows 10 on Chrome and Firefox for both free and premium users.

![trackers removed on each mask](https://user-images.githubusercontent.com/79697848/181575175-a9534428-abc6-49e6-999d-756f3d38a64d.png)

![trackers removed disabled](https://user-images.githubusercontent.com/79697848/181575212-c3cda662-f59a-41de-b9ec-299a49fb7ed6.png)
