### ISSUE TITLE
Can't create new masks if network.http.sendRefererHeader = 0

### ISSUE THREAD

**Issue by Z0pyrus** [mozilla/fx-private-relay#2530]
I hardened my Firefox Browser a little bit by setting `network.http.sendRefererHeader = 0`. This will cause an error while trying to create a new mask.

Firefox: 104.0.2 (64-Bit)

This is the log from the console:

```
{"detail":"CSRF Failed: Referer checking failed - no Referer."}

XHRPOSThttps://relay.firefox.com/api/v1/relayaddresses/                    [HTTP/2 403 Forbidden 184ms]
	
POST https://relay.firefox.com/api/v1/relayaddresses/
Status 403 Forbidden
VersionHTTP/2
Übertragen 3,20 KB (63 B Größe)
Referrer Policysame-origin
Anfrage-Priorität Highest

Awnser:
HTTP/2 403 Forbidden
server: openresty
date: Mon, 19 Sep 2022 09:50:52 GMT
content-type: application/json
content-length: 63
allow: GET, POST, HEAD, OPTIONS
referrer-policy: strict-origin-when-cross-origin
vary: Accept-Language, Origin, Cookie
content-language: de
x-frame-options: DENY
content-security-policy: default-src 'self'; img-src 'self' firefoxusercontent.com https://profile.accounts.firefox.com; style-src 'self' '
connect-src 'self' https://www.google-analytics.com/ https://accounts.firefox.com https://location.services.mozilla.com https://basket.mozilla.org; script-src 'self' https://www.google-analytics.com/
strict-transport-security: max-age=31536000
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
cache-control: private, no-cache, no-store, must-revalidate
via: 1.1 google
alt-svc: clear
X-Firefox-Spdy: h2

Request:
POST /api/v1/relayaddresses/ HTTP/2
Host: relay.firefox.com
Accept: application/json
Accept-Language: de
Accept-Encoding: gzip, deflate, br
content-type: application/json
Content-Length: 16
Origin: https://relay.firefox.com
DNT: 1
Connection: keep-alive
Cookie: sessionid=; first_visit="";
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
TE: trailers
```

**Comment by jwhitlock** [comment]
Support for the `Origin` header for CSRF checks was added in [Django 4.0](https://docs.djangoproject.com/en/4.1/ref/csrf/#how-it-works), but Relay is on version 3.2, the Long Term Support (LTS) version. We do not plan to upgrade Django until 4.2 is released and becomes the new LTS version. We'll require the `Referer` header until we update.

If you use an addon, you may be able to block the `Referer` header on other websites but allow it on Relay:

https://addons.mozilla.org/en-US/firefox/search/?q=referer

This document has other settings that tune the `Referer` header. `network.http.referer.trimmingPolicy=2` makes the `Referer` look like the `Origin` header, I believe. The document may be out of date, since it was last modified April 2018:

https://wiki.mozilla.org/Security/Referrer
