### ISSUE TITLE
Should not allow edits to the addresses

### ISSUE THREAD

**Issue by sandysage** [mozilla/fx-private-relay#262]
When an email address is generated, editing the email in the form field breaks the flow. For now, let's remove the ability to edit the email address at all.

**Comment by groovecoder** [comment]
We could do this easily by `readonly=true` to the `input` element, but we should be aware that it could cause significant form breakage.

We should DEFINITELY NOT use `disabled=true` because:

> disabled controls can not receive focus and are not submitted with the form and generally do not function as controls until they are enabled
([MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/readonly))

I propose we make this priority-P2 unless/until we get some user feedback suggesting it's a higher priority.

**Comment by groovecoder** [comment]
I think we decided to punt this out of the invite-only beta milestone since it could cause lots of site compat issues?
