### ISSUE TITLE
Editing labels on smaller screens

### ISSUE THREAD

**Issue by arashm** [mozilla/fx-private-relay#3090]
There doesn't seem to be any way to edit labels on smaller screens (mobile/tablets).

![Screenshot_20230213_202315_Firefox](https://user-images.githubusercontent.com/849640/218567339-3b74a49a-4078-4dc7-9348-2f9e651d95ec.jpg)
(Screenshot from tablet)

**Comment by Vinnl** [comment]
Hi @arashm, have you [enabled label sync](https://support.mozilla.org/en-US/kb/use-labels-keep-your-masks-organized-firefox-relay#w_get-your-labels-on-all-your-devices)? That allows us to store your labels on our servers and make them available on all your devices. Otherwise, labels will only be stored on a single device on which the extension is installed.

**Comment by arashm** [comment]
Thanks. Didn't know about that option.
