### ISSUE TITLE
[Addon] Private Relay doorhanger displays unintended scrollbars after signing in 

### ISSUE THREAD

**Issue by TimeaC** [mozilla/fx-private-relay#315]
**Affected Version**
Release Version 76.0.1 (64-bit)
Private Relay Add-on version 1.4.0

**Tested on**
Windows 10 x64
MacOS 10.15
Ubuntu 18.04

**Steps to reproduce:**
1. Launch latest Firefox Release
2. Install the latest Private Relay Add-on
3. Open the add-on doorhanger and choose to sign in
4. After you are signed in, click once more on the Private Relay button to toggle the doorhanger

**Expected:**
Private Relay doorhanger should be correctly displayed, without any unintended elements. 

**Actual:**
Vertical and horizontal scrollbars are displayed in the doorhanger. See the attached image:
![2020-05-20_10h59_47](https://user-images.githubusercontent.com/65650857/82422770-8cb49d00-9a8b-11ea-8032-389323af1e12.png)

**Comment by sv-hyacoub** [comment]
This issue is also reproducible on the Private Relay door-hanger. A vertical and horizontal scroll bars are displayed while singed out and signed in intro private relay account.
![Screenshot 2020-06-12 at 12 02 17](https://user-images.githubusercontent.com/15101135/84486610-50e5af80-aca6-11ea-870f-21ae7e9d49f4.png)

**Comment by sv-hyacoub** [comment]
The scroll bar is no longer displayed on Firefox 77.0.1 using Firefox Relay Beta add-on version 1.4.1 on Windows 10, Mac OS X 10.15 and on Ubuntu 18.04.
