### ISSUE TITLE
[Addon] Private Relay doorhanger is not closed after clicking on "Create Account" or on "Sign In buttons

### ISSUE THREAD

**Issue by sv-hyacoub** [mozilla/fx-private-relay#320]
### Affected versions

Firefox 76.0.1
Private Relay add-on version 1.4.0

### Affected platforms

Mac OS X 10.15
Windows 10 x64
Ubuntu 18.04 x64

### Steps to reproduce

1. Launch Firefox.
2. Install the Private Relay add-on.
3. In the Address Toolbar, click on the "Private Relay" button.
4. Click on "Create Account" or on "Sign In".

### Expected behavior

Private Relay doorhanger should be closed after clicking on "Create Account" or on "Sign In buttons.

### Actual behavior

Private Relay doorhanger is not closed after clicking on "Create Account" or on "Sign In buttons.

**Comment by sbadau** [comment]
The issue is reproducible also on the newest version of the add-on, the door-hanger is not dismissed when clicking on the "Sign up for the waitlist with your Firefox account" option. Please see the screencast for more details (tested on Firefox 77.0.1 and Private Relay 1.3.1)

![2020-06-16_09h26_17](https://user-images.githubusercontent.com/56026823/84739170-d7a2d100-afb3-11ea-9fdd-019cb71b5790.gif)

**Comment by sv-hyacoub** [comment]
Verified on Firefox 78.0.2 using Version 1.4.2 of Firefox Relay add-on on MacOS 10.14, Windows 10 x64 and on Ubuntu 18.04 x64.
