### ISSUE TITLE
[Website] Avoid use ISO3166 as country list on Private Network waitlist page

### ISSUE THREAD

**Issue by adsa562** [mozilla/fx-private-relay#346]
The current list in "Country" dropdown of Private Network waitlist is bad and controversial and offensive to some of our users.
Please refer to https://wiki.mozilla.org/Lists_of_Countries_and_Regions for best practice within Mozilla projects.

![screenshot of "country dropdown" list Taiwan as "Province of China"](https://user-images.githubusercontent.com/12174873/82686348-4f692e80-9c88-11ea-85ca-98453df8de1c.png)

**Comment by pdehaan** [comment]
@adsa562 Thank you very much for this report!

I've copied this issue over to the [private] https://fpn.firefox.com/ repo so that team can take a look at it.

Closing this issue since this repo is primarily for Firefox Private Relay project (versus the VPN project mentioned above). But I'll be sure to copy any further feedback here into the issue in the other repo.
