### ISSUE TITLE
Write test(s) for #3748

### ISSUE THREAD

**Issue by lloan** [mozilla/fx-private-relay#3797]
Write test for PR #3748 

Add a unit test that verifies that the banner is shown (and others are hidden) in the right circumstances.

**Comment by raffifu** [comment]
Hii, i'm interesting working on this issue. I have read the code and need to confirm the test of upsell banner should cover
1. upsell banner will shown If the user reach the limit
2. upsell banner should show correctly for user on US and non US

is there anything else? Because i can't open the Mozilla-hub jira so i can't check the requirement outside of the linked PR
