### ISSUE TITLE
Mozilla Devs you are the best, but where tf is my forwarded email! 

### ISSUE THREAD

**Issue by Uniquecrete** [mozilla/fx-private-relay#4413]
Hi. So this is my first time using the relay, but since it's pre-release I thought I might leave my 2¢ here. I am using a Moto G 5G (2022), and the Play Store holds no updates for my Gmail app, or for Firefox, and my OS (Android 13) says it is up-to-date as well. 

Sorry about the title, but I just spent about 10-15 minutes trying to find a password reset email that was sent to one of my gmail accounts and every one of those minutes beyond the first 3 of them felt like I was banging my head against a wall for about a lifetime. 

Okay, but the thing is even after I found it (via search all inboxes) and determining for certain which address held it, I still could not find it and I still have no idea where it resides. I mean it was not in Spam, Primary or all mail. 

Maybe take a look at making something about the first use more guided or perhaps intuitive.? Idk you guys are the magic weavers and what you're doing here is really a godsend, but if folks have a similar experience as I just did it may turn them away from Firefox Relay.

I could see the relay being the reason some people try firefox out, and it would suck if they didn't really give it a chance because they were no smarter than I am and couldn't figure out how to use the relay even after figuring out how to use the relay like i did. 

Thanks! 

PS- Idk how to use a github either so idk if this was the appropriate place for this or not, but I will both:
-check back here if I can remember to see if you guys had any questions for me, and
-totally not be offended if you just close this issue without reply or without taking action just because I had a hard time on my first attempt to use the relay.

**Comment by jwhitlock** [comment]
Thanks for reaching out @Uniquecrete, and congrats for finding the GitHub project.

> Okay, but the thing is even after I found it (via search all inboxes) and determining for certain which address held it, I still could not find it and I still have no idea where it resides. I mean it was not in Spam, Primary or all mail.

I'm glad you found it. "Where it is" sounds like a gmail issue. If you can try on https://mail.google.com, the web interface may make it clearer how the email was tagged.

> Maybe take a look at making something about the first use more guided or perhaps intuitive.?

We added a feature to relay.firefox.com that guides users through creating their first mask, and we send an email to the mask to help user see where these arrive and what they look like. Thank you for the feedback that this was not enough.

> I could see the relay being the reason some people try firefox out, and it would suck if they didn't really give it a chance because they were no smarter than I am and couldn't figure out how to use the relay even after figuring out how to use the relay like i did.

A lot of people do not intuitively understand how Relay works. I think this is not a matter of being smart or experienced. I think there is a gap between how people expect it to work and what we're providing. We've done some research (surveys, interviews, etc.), and tuned the text on the websites, but the gap remains. If you can describe how you think it would work, that may help.

> totally not be offended if you just close this issue without reply or without taking action just because I had a hard time on my first attempt to use the relay.

I appreciate that, because I'm going to close this issue. Feel free to respond, but I don't see a bug or suggested feature here, so I'm not sure what the next action is, other than a response.

For future Relay users that find this thread, if you are having an issue with Relay please take a look at our support site, https://support.mozilla.org/en-US/products/relay. If the pages do not address your issue, you can continue on the site with a few clicks to open a support issue. This will start a private thread with our support team, where we can ask for details like account IDs and emails to diagnose issues. It is unsafe to share these details on a public website like GitHub.
