### ISSUE TITLE
[Website] The "delete" warning-text wraps the email address partway through, if it lands at the end of a line

### ISSUE THREAD

**Issue by dholbert** [mozilla/fx-private-relay#467]
STR:
1. Visit https://relay.firefox.com/accounts/profile/
2. Click "Show Details" and then "Delete" for one of your relay addresses.

ACTUAL RESULTS: The red warning text saying `Firefox Relay will no longer forward messages to [your-random-string]@relay.firefox.com`  is linewrapped in the middle of the email address.

EXPECTED RESULTS: No such linewrapping.  The email address should be shown on a single line, if possible, probably?  It looks broken the way it is right now.

This happens because the alias is wrapped in `<span class="alias-to-delete">`, which style.css blesses with the declaration `word-break: break-all`, which explicitly means "linewrap anywhere you like in this string".

Here's a screenshot:
![image](https://user-images.githubusercontent.com/426803/85335920-a4b87b80-b492-11ea-8c42-3384bd360163.png)

**Comment by joaonunomota** [comment]
The email address now has the expected results as it is no longer broken into separate lines before it becomes wider than the paragraph containing it.

The email address is wrapped in `<strong>` instead of `<span class="alias-to-delete">`, and no longer has the rule `word-break: break-all` applied to it.

This is what it looks like now with a small the viewport:

<img src="https://user-images.githubusercontent.com/16689477/235220723-152b6e23-6412-4c8c-bd69-b1285951cb46.png" width="auto" height="600">

**Comment by jwhitlock** [comment]
Thanks @joaonunomota!
