### ISSUE TITLE
HTML in mail not rendered properly

### ISSUE THREAD

**Issue by MarcDirven** [mozilla/fx-private-relay#4841]
If I receive an e-mail in my "Other" mail or "Non prioritized", HTML is not rendered properly:
![image](https://github.com/mozilla/fx-private-relay/assets/31624073/72029291-8e31-490c-9144-f35a11817627)
![image](https://github.com/mozilla/fx-private-relay/assets/31624073/beee7df7-4d55-4d38-b257-32290b8cbf75)

This only happens in that specific tab, not in my main e-mail tab.

**Comment by jwhitlock** [comment]
What email client is this? 

The email headers seem correct:

```
Content-Type: text/html; charset="utf-8"
Content-Transfer-Encoding: quoted-printable
```
The content looks like [quoted-printable](https://en.wikipedia.org/wiki/Quoted-printable) content. Since it only happens in one tab, this seems like an email client issue.

**Comment by MarcDirven** [comment]
This is [outlook.live.com](url). I wasn't sure whether this was a FFR problem or a mail client problem, problem only happens with FFR in "Other" e-mail tab.

**Comment by jwhitlock** [comment]
I created an outlook.com account and a paired Relay account. I have not been able to reproduce this yet, but I also haven't been able to send a similar email with `Content-Type: text/html; charset="utf-8"`. 
Mails from Gmail and Yahoo end up with a a header `Content-Type: multipart/alternative; boundary="000..."`, with the HTML and text content in MIME multipart sections.

Can you tell me more about the source of this email? If not, I can move on to simulating the email in tests.

**Comment by MarcDirven** [comment]
Well the source is info@alloverpiercings.com and the other one (the correctly rendered one that is) is some cryptic icloud account (info_at_draaimolen_nu_2v4ff4tvbb2230_dadb0052@icloud.com).

It is not the first time this happened by the way. This happened to me once earlier but their website was very yanky, so I thought: "oh well if their website is yanky then so are their e-mails probably", but maybe I guessed wrong. The sender/source of that very first incident was vinylminded-321@mail.common-ground.io. The actual mail I do not have anymore since I deleted that a while ago.

**Comment by jwhitlock** [comment]
As a backend dev, that makes some sense. Promotional emails are often sent by mass email systems that are tuned to work as widely as possible and get into your inbox. Order confirmation emails and transactional emails are sent by backend systems and the developer stops when it works for them...

Thank you sharing the website. I was able to sign up for an account. The "Thank you for registering" email renders correctly. I added to my site wishlist and sent that to a second email mask. That email, "The All Over Piercings Wishlist of John.", has the rendering issue. I get the issue in "Focused" and in "Other" (I drag the email to the tab title to move the email.

Now that I can replicate the issue, I can see what I can do to fix it. Sorry, this may take a few weeks to fix.

**Comment by MarcDirven** [comment]
Thanks and no problem! So this is a backend issue caused by its developers? Never saw this before except with FFR.

**Comment by jwhitlock** [comment]
> Thanks and no problem! So this is a backend issue caused by its developers? Never saw this before except with FFR.

That's a great point - I missed a debugging step. If I send the wishlist directly to my outlook email, there is _no_ rendering issued in Focused or Other (although it does seem to take a second to render). This is a FFR issue with emails constructed this particular way, probably a source email header that we are not setting in the relayed email.

**Comment by MarcDirven** [comment]
Sounds good, you're doing great work ✌🏼

**Comment by jwhitlock** [comment]
The issue was the subject header. Mine is:

```email
Subject: The All Over Piercings Wishlist of =?UTF-8?Q?John=2E=0A?=
```

The `=?UTF-8?Q?` bit starts a utf-8 encoded section. They may have done this to allow non-ASCII first names, but applied it unconditionally, since my name `John` doesn't need it. This may be a feature of Drupal, the PHP application engine used by the site (as show by a `Drupal` variable in the site javascript, as well as the `X-Mailer: Drupal` header in the email). Or, the site may be _trying_ to put a newline in the subject, in order to make it stand out in your inbox.

The first part of the utf-8 encoded section is my name in ASCII (`John`). Next, the characters `=2E` represents a period `.`. The `=0A` is a new line character `\n`. `?=` ends the utf-8 encoded section.

The issue is that the forwarding code uses the decoded unicode string `The All Over Piercings Wishlist of John.\n`. The Python library code does not reject the string with a trailing newline (it rejects any other newline), and the email encoding code doesn't detect that it needs to escape the newline. I filed this upstream (https://github.com/python/cpython/issues/121650).

The email has a newline character right after the `Subject` header. This is how you separate the email headers from the email content. For this particular email, the headers that say the content is HTML (`Content-Type: text/html; charset=UTF-8`) are _after_ the subject. So, your email client falls back to treating it as a plain text email, and you see some email headers followed by the raw email.

If my name _did_ include a non-ASCII character, like `Seán`, then Python would have encoded the newline, like `=?utf-8?Q?Se=C3=81n=2E=0A?=`, and it would have been rendered correctly. So I guess changing your name is another solution?

If the `Subject` appeared before other headers like the `To` header, and the email would not be delivered at all. There may be other Relay emails not being delivered because of this issue,=.

I can fix this on the Relay side, and a future Python release will fix it on the Python side. Thanks for the interesting and important bug!

**Comment by MarcDirven** [comment]
Very interesting read. I changed my name officially to Márque (kiddings of course).

Also "fun" to see that this is a minor security risk

**Comment by jwhitlock** [comment]
This fix is now on relay.firefox.com. I was able to send the wishlist to a Relay mask, and it displayed correctly, despite the encoded newline in the subject.

**Comment by MarcDirven** [comment]
Thanks!
