### ISSUE TITLE
Home page: "Download the ⁨Relay⁩ extension for ⁨Firefox" link broken

### ISSUE THREAD

**Issue by groovecoder** [mozilla/fx-private-relay#952]
STR:

1. Go to relay.firefox.com
2. Scroll to "How It Works"
3. Click the "Download the ⁨Relay⁩ extension for ⁨Firefox" under the "Install the extension" section

Expected results:
Get to https://addons.mozilla.org/en-US/firefox/addon/private-relay/

Actual results:
404 at https://relay.firefox.com/%E2%81%A8https://addons.mozilla.org/firefox/addon/private-relay/%E2%81%A9

**Comment by Bianca-O** [comment]
This issue is verified as fixed on Stage and Production under Windows 10 64 bit and macOS 10.14. The link redirects to https://addons.mozilla.org/en-US/firefox/addon/private-relay/.
 See new situation:
![link - new situation](https://user-images.githubusercontent.com/79697848/129682330-f2ba5210-2d6f-4841-9780-2360c90e1588.gif)
